### ISSUE TITLE
Search Box Broken

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#49]
The Search box top right on current web rendered docs is broken in that it always returns no entries.

**Comment by phillxnet** [comment]
I suspect this is due to the wrong jquery.js being used by doctools.js
It seems _static/jquery is 1.7.2 when build locally and 1.11.1 on web !
```
Uncaught TypeError: $.getQueryParameters is not a function
Documentation.highlightSearchWords	@	doctools.js:192
Documentation.init	@	doctools.js:125
(anonymous function)	@	doctools.js:262
m.Callbacks.j	@	jquery.js:2
m.Callbacks.k.fireWith	@	jquery.js:2
m.extend.ready	@	jquery.js:2
J	@	jquery.js:2
```
in chrome developer tools on every page.
Nearest hint I can find so far is:-
https://github.com/spinus/sphinxcontrib-images/issues/13
"
This is related to the fact that Lightbox2 is using its own version of jQuery. I'm not sure if this is really needed. After including jquery-1.11.0.min.js, sphinx search script is unhappy with the content of $.

Anyway, I'm no JS expert, but I fixed it by calling jQuery.noConflict(true) after including everything related to lightbox.
"
So not really my area obviously but pasting here as a clue.

**Comment by schakrava** [comment]
Thank you sir! That ended up being just the right hint I needed to fix the search box. Back when we created a custom theme, we used the older jquery which is not only not necessary, but inadvertently broke the search box. 

Anyway, I think it's fixed now. I've also changed the css a bit. @phillxnet, I've uploaded the latest docs to the website. @priyaganti is the one that normally makes the design changes. So, please do list your suggestions, if you have any.

**Comment by phillxnet** [comment]
@schakrava That's great, well done. I'm chuffed that this one is done and dusted.

Closing as "now works for me" in Chrome and Firefox. It's quite a nice search facility as well. I've never actually seen it work. Great.

**Comment by phillxnet** [comment]
@schakrava 
Ok, never mind.  We still have a little problem:- fails when tested on the sub-directory stored sections:-

Rock-ons (Docker Plugins):-
"The requested URL /docs/docker-based-rock-ons/search.html was not found on this server."
Re-installing Rockstor:-
 "The requested URL /docs/reinstall/search.html was not found on this server."

And it's not a pretty one either ie 404
However it does work beutifully everywhere else I've tried.

**Comment by phillxnet** [comment]
Pull request #73 ready for review to hopefully fix this last sub part of this issue.
